### ISSUE TITLE
percentiles source

### ISSUE THREAD

**Issue by mbrevda** [TomSadeh/deciles#1]
Hi - can you kindly share the source of the percentiles? Thanks!

**Comment by TomSadeh** [comment]
Hey - the source is the PUF of Expenditure Survey 2021 by the CBS.
You need to [fill a form and request the relevant files](https://www.cbs.gov.il/he/publications/Pages/2015/%D7%AA%D7%95%D7%A6%D7%A8%D7%99-Public-Use-Files-PUF-%D7%A0%D7%AA%D7%95%D7%A0%D7%99-%D7%A4%D7%A8%D7%98-%D7%91%D7%9C%D7%AA%D7%99-%D7%9E%D7%96%D7%95%D7%94%D7%99%D7%9D-%D7%9C%D7%9E%D7%97%D7%A7%D7%A8.aspx), and the CBS sends them to you after a short while (usually a day).

I cannot upload the files to Github as it's against the use license.
The calculation of the quantiles is with statsmodels.stats.weightstats.DescrStatsW and it's about 4 or 5 lines of code, and as I cannot upload the file I didn't include it in the repo.

**Comment by mbrevda** [comment]
>  fill a form 

Too much hassle. Thanks!
